arch: resnet18
batch_size: 128
dataset: h
exclude_bn_bias: false
feat_dim: 128
final_lr: 0.001
first_conv: true
gpus: 1
hidden_mlp: 2048
learning_rate: 0.001
max_epochs: 100
maxpool1: true
num_nodes: 1
num_samples: 0
optimizer: adam
start_lr: 0.001
strict: false
temperature: 0.1
warmup_epochs: 10
weight_decay: 1.0e-06
