arch: resnet50
batch_size: 64
data_path: /datasets01/imagenet_full_size/061417
dataset: imagenet
exclude_bn_bias: false
fast_dev_run: false
feat_dim: 128
final_lr: 0.0048
first_conv: true
fp32: false
gaussian_blur: true
gpus: 8
hidden_mlp: 2048
input_height: 224
jitter_strength: 1.0
lars_wrapper: true
learning_rate: 4.8
max_epochs: 800
max_steps: -1
maxpool1: true
meta_dir: /checkpoint/tullie
nodes: 8
num_nodes: 1
num_samples: 1231167
num_workers: 8
online_ft: true
optimizer: adam
resume_from_checkpoint: ./lightning_logs/version_33125347/checkpoints/epoch=635.ckpt
start_lr: 0.3
temperature: 0.1
warmup_epochs: 10
weight_decay: 1.0e-06
